# Generated by Django 4.1 on 2022-08-04 10:33

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(default='', max_length=300, unique=True, verbose_name='Slug (Auto-complete)')),
                ('description', models.CharField(max_length=300, verbose_name='Short Description')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('isActive', models.BooleanField(default=False, verbose_name='Active / Inactive')),
                ('isDelete', models.BooleanField(verbose_name='Deleted')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Title')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='Url Title')),
                ('isActive', models.BooleanField(default=False, verbose_name='Active / Inactive')),
                ('isDelete', models.BooleanField(verbose_name='Deleted')),
            ],
            options={
                'verbose_name': 'Post Category',
                'verbose_name_plural': 'Post Categories',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=300, verbose_name='Caption')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='post.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': "Post's tag",
                'verbose_name_plural': "Post's tag",
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='post_categories', to='post.postcategory', verbose_name='Categories'),
        ),
    ]
