# Generated by Django 4.1 on 2022-08-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images/<built-in function id>-<django.db.models.fields.DateTimeField>/', verbose_name='Image'),
        ),
    ]
