# Generated by Django 4.0.6 on 2022-08-01 09:18

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_date_alter_post_image_alter_post_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.upload_image_path),
        ),
    ]
