# Generated by Django 4.1 on 2022-08-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='assets/img/no-photo-available-icon-13.jpg', null=True, upload_to='post_images/', verbose_name='Image'),
        ),
    ]
