# Generated by Django 4.1 on 2022-08-15 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0011_remove_postcategory_parent_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create Date')),
                ('isApproved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('comment_text', models.TextField(db_index=True, verbose_name='Text ')),
                ('indicated_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Post ')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.postcomment', verbose_name='Parent comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ')),
            ],
        ),
    ]
