# Generated by Django 4.1 on 2022-08-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_postcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='indicated_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='posts', to='post.post', verbose_name='Post '),
        ),
    ]
