# Generated by Django 4.1 on 2022-08-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message from Client')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response from Admin')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('isRead', models.BooleanField(default=False, verbose_name='Is the message read by the Admin')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Attached')),
            ],
            options={
                'verbose_name': 'Contact Module',
                'verbose_name_plural': "Contact Form's",
            },
        ),
    ]
