# Generated by Django 4.1 on 2022-08-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Attached'),
        ),
    ]
