# Generated by Django 4.1 on 2022-08-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sitesettings_options_alter_skills_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Social media platform')),
                ('account_link', models.CharField(max_length=200, verbose_name='Account reference link')),
            ],
            options={
                'verbose_name': 'Social Media Account',
                'verbose_name_plural': "Social Media Account's",
            },
        ),
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getInTouchText', models.TextField(verbose_name='Get in touch text')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address ')),
                ('phone_number', models.CharField(max_length=150, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address ')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.socialmediaaccounts', verbose_name='Social media accounts')),
            ],
            options={
                'verbose_name': 'Get in touch',
                'verbose_name_plural': 'Get in touch module',
            },
        ),
    ]
