# Generated by Django 4.1 on 2022-08-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_hero_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='skills',
        ),
        migrations.AddField(
            model_name='hero',
            name='skills',
            field=models.ManyToManyField(to='home.skills', verbose_name='Skills '),
        ),
    ]
