# Generated by Django 4.1 on 2022-08-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_hero_skills_hero_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='short_description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='skills',
            field=models.ManyToManyField(to='home.skills', verbose_name='Skills'),
        ),
    ]
