# Generated by Django 4.1 on 2022-08-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_getintouch_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address '),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.socialmediaaccounts', verbose_name='Social media accounts'),
        ),
    ]
