# Generated by Django 4.1 on 2022-08-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_getintouch_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getintouch',
            name='social_media',
        ),
        migrations.AddField(
            model_name='getintouch',
            name='social_media',
            field=models.ManyToManyField(blank=True, null=True, to='home.socialmediaaccounts', verbose_name='Social media accounts'),
        ),
    ]
