# Generated by Django 4.1 on 2022-08-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_getintouch_social_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='home.socialmediaaccounts', verbose_name='Social media accounts'),
        ),
    ]
