# Generated by Django 4.1 on 2022-08-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_getintouch_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='social_media',
            field=models.ManyToManyField(blank=True, related_name='platforms', to='home.socialmediaaccounts', verbose_name='Social media accounts'),
        ),
    ]
