# Generated by Django 4.1 on 2022-08-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_getintouch_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccounts',
            name='account_link',
            field=models.URLField(verbose_name='Account reference link'),
        ),
    ]
