# Generated by Django 4.1 on 2022-08-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='isMain',
            field=models.BooleanField(default=False, verbose_name='Main Meta Tags for Site'),
        ),
    ]
