# Generated by Django 4.1 on 2022-08-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_seo_ismain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, verbose_name='Keywords Meta Tag')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.RemoveField(
            model_name='seo',
            name='keywords',
        ),
        migrations.AddField(
            model_name='seo',
            name='keywords_connection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='home.keywords', verbose_name='Keywords'),
            preserve_default=False,
        ),
    ]
