# Generated by Django 4.1 on 2022-08-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_keywords_remove_seo_keywords_seo_keywords_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='keywords_connection',
        ),
        migrations.AddField(
            model_name='seo',
            name='keywords_connection',
            field=models.ManyToManyField(to='home.keywords', verbose_name='Keywords'),
        ),
    ]
