# Generated by Django 4.1 on 2022-08-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_seo_keywords_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='keywords_connection',
            field=models.ManyToManyField(related_name='keywords_for_seo', to='home.keywords', verbose_name='Keywords'),
        ),
    ]
