# Generated by Django 4.1 on 2022-08-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_iplog_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.iplog', verbose_name='Visitor '),
        ),
    ]
