# Generated by Django 4.1 on 2022-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_visitors_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iplog',
            options={'verbose_name': 'Logged ip', 'verbose_name_plural': "Logged IP's"},
        ),
        migrations.AddField(
            model_name='iplog',
            name='visits_count',
            field=models.IntegerField(default=0, verbose_name='Count of Visitors'),
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
