# Generated by Django 4.1 on 2022-08-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_iplog_options_iplog_visits_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplog',
            name='visits_count',
            field=models.IntegerField(verbose_name='Count of Visitors'),
        ),
    ]
