# Generated by Django 4.1 on 2022-08-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_iplog_visits_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iplog',
            name='visits_count',
        ),
    ]
