# Generated by Django 4.1 on 2022-08-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_iplog_visits_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplog',
            name='visits_count',
            field=models.IntegerField(default=0, verbose_name='Count of Visitors'),
        ),
    ]
